name: fear_and_hunger_localization_tool
description: 'Herramienta de asistencia para traducir y analizar textos de Fear & Hunger y Fear & Hunger 2: Termina'
publish_to: 'none'

# Lo siguiente define la versión y el número de construcción para tu aplicación.
# Un número de versión son tres números separados por puntos, como 1.2.43
# seguido de un número de construcción opcional separado por un +.
# Tanto el número de versión como el de construcción pueden ser reemplazados en la construcción de flutter
# especificando --build-name y --build-number, respectivamente.
# En Windows, build-name se usa como las partes mayores, menores y de parche
# de las versiones del producto y del archivo mientras que build-number se usa como el sufijo de construcción.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Las dependencias especifican otros paquetes que tu paquete necesita para funcionar.
# Para actualizar automáticamente las dependencias de tu paquete a las últimas versiones
# considera ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias pueden ser actualizadas manualmente cambiando los números de versión debajo a
# la última versión disponible en pub.dev. Para ver qué dependencias tienen versiones más nuevas disponibles, ejecuta `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

# Para información sobre la parte genérica de Dart de este archivo, ve la
# siguiente página: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica para los paquetes de Flutter.
flutter:

  # La siguiente línea asegura que la fuente de los íconos Material se
  # incluye en tu aplicación, para que puedas usar los íconos en la
  # clase Material Icons.
  uses-material-design: true

  # Para agregar activos a tu aplicación, añade una sección de activos, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Un activo de imagen puede referirse a una o más "variantes" específicas de resolución, ve
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Para detalles sobre cómo agregar activos desde dependencias de paquetes, ve
  # https://flutter.dev/assets-and-images/#from-packages

  # Para agregar fuentes personalizadas a tu aplicación, añade una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debería tener una
  # clave "family" con el nombre de la familia de la fuente, y una clave "fonts" con una
  # lista proporcionando el activo y otros descriptores para la fuente. Por
  # ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalles sobre fuentes desde dependencias de paquetes,
  # ve https://flutter.dev/custom-fonts/#from-packages
